### PR TITLE
Stack Loader entity added, AAI Industries recipes made optional, languages other than en removed (need assistance translating), 

### PR DESCRIPTION
**Pull request by jcclark1414**
Features:
    - Setting added when AAI-Industry is detected which allows user to choose to use AAI-Industry recipe or base recipe
    - Stack Loader entity added
      - Effectively this is a turbo loader with stacking capabilities recolored white to match stack loader. 
      - Recipe required turbo loader, stack inserts, and processing units
      - Setting added to enable or disable Stack Loader
      - Stack Loader whitelisted to always allow stacking, even if 'None' is selected in stacking settings
  Changes:
    - RU locale removed
    - DE locale removed
    
    Notes:
    - First implementation, has not been tested with 5Dmins loaders, is working effectively with AAI loaders.
    - Did not add more expensive recipe for AAI loaders, this could be done later
    - Icon 'Stack Loader' sits in front of 'Turbo Loader' in the item UI list, ideally this would be corrected but I could not figure out how to.
    - Bugfix grammar to be edited for consistency
    - thumbnail change optional, change was made for personal server use to set mods apart temporarily

### CODE REVIEW

**Comment by jcclark1414** [comment]
Incredible work here, kryojenik, best Loader mod in Factorio.

This may or may not fit with what you intend for this mod, but I do think it's a valuable addition when implemented as a fully optional entity

The idea behind this tweak is to allow players to either enable turbo loaders with stacking (which should cost stack inserters), or enable turbo loaders without stacking (which don't cost stack inserters) + the new 'Stack Loader' entity which does do the stacking.

Also, simply added a setting to make AAI Industries recipes optional, to enable using AAI for graphics only

**Comment by kryojenik** [comment]
Thanks!   I will definitely take a look this week.   I've been struggling how to appropriately balance things.  I didn't like stacking not requiring stacking inserters.   Using the AAI Loaders graphics doesn't require AAI Industry though, so simply using the graphic shouldn't change the recipe.   However, I'm keen to making that an option vs. forcing it with AAI Industry.

**Comment by kryojenik** [comment]
I merged this PR in.  Thanks!  Apparently I didn't do it exactly the way github wanted me to, so it didn't auto-close.

**Comment by jcclark1414** [comment]
Works for me! First pull request for me as well, so inevitably I probably did something silly

Let me know when it goes live on the Factorio mod page and I'll switch our world file over to the updated one =D

**Comment by kryojenik** [comment]
Hey, forgot to update here.  Updates were published the other day.   There are a few changes.  Let me know if its working the way you hoped.

**Pull request closed without merging**
